services:
  - type: web
    name: sms-spam-classifier
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: python app_flask.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: NLTK_DATA
        value: /opt/render/.cache/nltk_data
